version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: facebook_insights
      MYSQL_USER: root
      MYSQL_PASSWORD: root // Change this to your password
      MYSQL_ROOT_PASSWORD: root   // Change this to your password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  celery:
    build: .
    container_name: celery_worker
    restart: always
    command: celery -A insights_microservice worker --loglevel=info
    depends_on:
      - db
      - redis
      - web
    env_file:
      - .env

volumes:
  mysql_data:
