# Generated by Django 5.1.5 on 2025-02-04 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_url', models.URLField(blank=True, null=True)),
                ('fb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('total_followers', models.IntegerField(blank=True, null=True)),
                ('total_likes', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post_url', models.URLField()),
                ('likes', models.IntegerField()),
                ('comments_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='insights.facebookpage')),
            ],
        ),
    ]
